#pragma once

#define WS2812_DI_PIN B15
#define WS2812_PWM_DRIVER PWMD1
#define WS2812_PWM_CHANNEL 3
#define WS2812_PWM_COMPLEMENTARY_OUTPUT
#define WS2812_PWM_PAL_MODE 1
#define WS2812_PWM_DMA_STREAM STM32_DMA1_STREAM5
#define WS2812_PWM_DMA_CHANNEL 1


#define MASTER_RIGHT
// #define SPLIT_HAND_MATRIX_GRID A1, A10
#define SERIAL_USART_FULL_DUPLEX   // Enable full duplex operation mode.
#define SERIAL_USART_TX_PIN B10    // USART TX pin
#define SERIAL_USART_RX_PIN B11    // USART RX pin
#define SERIAL_USART_DRIVER SD3
// #define SPLIT_TRANSPORT_MIRROR
// #define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
// #define SPLIT_MODS_ENABLE
// #define SPLIT_WPM_ENABLE
// #define SPLIT_OLED_ENABLE
// #define SPLIT_HAPTIC_ENABLE

/* RGB灯光 */

#ifdef RGB_MATRIX_ENABLE
    #define RGB_MATRIX_FRAMEBUFFER_EFFECTS
    #define RGB_MATRIX_KEYPRESSES
    #define RGB_SLEEP
    #define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_CYCLE_LEFT_RIGHT
#endif

#define ENCODER_A_PINS { NO_PIN }
#define ENCODER_B_PINS { NO_PIN }
